// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow that suggests a relevant photo based on a user-provided quote.
 *
 * @fileOverview A photo suggestion AI agent.
 *  suggestPhotoForQuote - A function that suggests a relevant photo for a quote.
 *  SuggestPhotoForQuoteInput - The input type for the suggestPhotoForQuote function.
 *  SuggestPhotoForQuoteOutput - The return type for the suggestPhotoForQuote function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestPhotoForQuoteInputSchema = z.object({
  quote: z.string().describe('The quote provided by the user.'),
});
export type SuggestPhotoForQuoteInput = z.infer<typeof SuggestPhotoForQuoteInputSchema>;

const SuggestPhotoForQuoteOutputSchema = z.object({
  photoSuggestion: z
    .string()
    .describe(
      'A one or two word suggestion for a photo that matches the quote.'
    ),
});
export type SuggestPhotoForQuoteOutput = z.infer<typeof SuggestPhotoForQuoteOutputSchema>;

export async function suggestPhotoForQuote(input: SuggestPhotoForQuoteInput): Promise<SuggestPhotoForQuoteOutput> {
  return suggestPhotoForQuoteFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestPhotoForQuotePrompt',
  input: {schema: SuggestPhotoForQuoteInputSchema},
  output: {schema: SuggestPhotoForQuoteOutputSchema},
  prompt: `You are an AI assistant that suggests a photo to accompany a quote.

  Based on the following quote, suggest a one or two word concept for a photo.

  Quote: {{{quote}}}

  If the quote is about love, suggest 'people in love'. If the quote is about nature, suggest 'nature'. If the quote is about sadness, suggest 'sadness'.
`,
});

const suggestPhotoForQuoteFlow = ai.defineFlow(
  {
    name: 'suggestPhotoForQuoteFlow',
    inputSchema: SuggestPhotoForQuoteInputSchema,
    outputSchema: SuggestPhotoForQuoteOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
